# Generated by Django 4.2.25 on 2025-10-03 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('ad_login', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='AD-логин')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Общий пароль')),
                ('ad_password', models.CharField(blank=True, max_length=128, verbose_name='Пароль AD')),
                ('email_password', models.CharField(blank=True, max_length=128, verbose_name='Пароль Email')),
                ('b24_password', models.CharField(blank=True, max_length=128, verbose_name='Пароль Б24')),
                ('sip_number', models.CharField(blank=True, max_length=20, verbose_name='SIP-номер')),
                ('b24_login', models.CharField(blank=True, max_length=100, verbose_name='Логин Б24')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='Отдел')),
                ('office', models.CharField(choices=[('ORL', 'Орёл'), ('MSK', 'Москва'), ('SKLAD', 'Склад'), ('remote', 'Удалёнка'), ('ЭМКО', 'ЭМКО')], max_length=20, verbose_name='Офис')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('dismissed', 'Уволен'), ('maternity', 'Декрет')], default='active', max_length=20, verbose_name='Статус')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения/выхода в декрет')),
                ('info', models.TextField(blank=True, verbose_name='Доп. информация (ЦКП и т.п.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee', verbose_name='Руководитель')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SIP', 'SIP-телефон'), ('Монитор', 'Монитор'), ('Ноутбук', 'Ноутбук'), ('Android', 'Android-устройство'), ('PC', 'Стационарный ПК'), ('-', 'Прочее')], max_length=50, verbose_name='Тип ТМЦ')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Серийный номер')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC-адрес')),
                ('ip_or_anydesk', models.CharField(blank=True, max_length=100, verbose_name='IP / AnyDesk')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('in_domain', models.BooleanField(default=False, verbose_name='В домене')),
                ('office', models.CharField(choices=[('ORL', 'Орёл'), ('MSK', 'Москва'), ('SKLAD', 'Склад'), ('remote', 'Удалёнка'), ('ЭМКО', 'ЭМКО')], max_length=20, verbose_name='Офис')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('disposed', models.BooleanField(default=False, verbose_name='Списано')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.employee', verbose_name='Сотрудник')),
            ],
        ),
    ]
