# Generated by Django 4.2.25 on 2025-10-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AddField(
            model_name='employee',
            name='pass_3cx',
            field=models.CharField(blank=True, max_length=128, verbose_name='Пароль 3CX'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tel_b24_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тел Б24 логин'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tel_b24_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тел Б24 пароль'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vats_login',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ватс логин'),
        ),
        migrations.AddField(
            model_name='employee',
            name='vats_password',
            field=models.CharField(blank=True, max_length=128, verbose_name='ВАТС пароль'),
        ),
        migrations.AddField(
            model_name='employee',
            name='web_3cx',
            field=models.CharField(blank=True, max_length=255, verbose_name='3CX WEB'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='info',
            field=models.TextField(blank=True, verbose_name='Инфо'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(choices=[('ORL', 'Орёл'), ('MSK', 'Москва'), ('SKLAD', 'Склад'), ('remote', 'Удалёнка'), ('ЭМКО', 'ЭМКО'), ('ORUS', 'ОРУС')], max_length=20, verbose_name='Офис'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='office',
            field=models.CharField(choices=[('ORL', 'Орёл'), ('MSK', 'Москва'), ('SKLAD', 'Склад'), ('remote', 'Удалёнка'), ('ЭМКО', 'ЭМКО'), ('ORUS', 'ОРУС')], max_length=20, verbose_name='Офис'),
        ),
    ]
